### ISSUE TITLE
Update Velero addon to v4.x

### ISSUE THREAD

**Issue by bryantbiggs** [aws-ia/terraform-aws-eks-blueprints-addons#287]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

- Update Velero addon to v4.x

#### Describe the solution you would like

- Updated Velero to the latest major version. Since this is a major version change for the chart, there is most likely breaking changes to the values/schema used

#### Additional context

https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/f039cda83fc0902c398684387d95df9beb0143f6/main.tf#L3341

**Comment by csantanapr** [comment]
@bryantbiggs velero latest chart is 5.x not 4.0
To use 5.x here is the new structure of the helm values compatible with v5.x

This is already supported in gitops-bridge we need equivalent in addons v2.0
https://github.com/aws-samples/eks-blueprints-add-ons/blob/main/argocd/bootstrap/control-plane/addons/aws/addons-aws-oss-velero-appset.yaml#L60-L85

```yaml
            values: |
              configuration:
                backupStorageLocation:
                - name: default
                  provider: aws
                  prefix: {{metadata.annotations.velero_backup_s3_bucket_prefix}}
                  bucket: {{metadata.annotations.velero_backup_s3_bucket_name}}
                  config:
                    region: {{metadata.annotations.aws_region}}
                volumeSnapshotLocation:
                - name: default
                  provider: aws
                  config:
                    region: {{metadata.annotations.aws_region}}
              serviceAccount:
                server:
                  name: {{metadata.annotations.velero_service_account}}
                  annotations:
                    eks.amazonaws.com/role-arn: {{metadata.annotations.velero_iam_role_arn}}
              initContainers:
              - name: velero-plugin-for-aws
                image: velero/velero-plugin-for-aws:v1.7.1
                imagePullPolicy: IfNotPresent
                volumeMounts:
                  - mountPath: /target
                    name: plugins
```
