### ISSUE TITLE
fix indentation in karpenter pause deployment docs

### ISSUE THREAD

**Issue by todd-dsm** [aws-ia/terraform-aws-eks-blueprints-addons#336]
## Description

This is an easy one; the karpenter docs use a pause container to demo deployments. The [yaml declaration](https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/99520ae0125df7b24163e14cf4eba2c96fcf14bd/docs/addons/karpenter.md?plain=1#L66-L67) needs to be properly indented; it looks like a simple copy/paste issue:

From:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: inflate
spec:
    replicas: 0
    selector:
    matchLabels:
        app: inflate
    template:
    metadata:
        labels:
        app: inflate
    spec:
        terminationGracePeriodSeconds: 0
        containers:
        - name: inflate
            image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
            resources:
            requests:
                cpu: 1
```

Target:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  replicas: 0
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
          resources:
            requests:
              cpu: 1

```
