### ISSUE TITLE
AccessDenied: User: assumed-role/karpenter is not authorized to perform: iam:PassRole on resource: karpenter-reproduction because no identity-based policy allows the iam:PassRole action

### ISSUE THREAD

**Issue by vstthomas** [aws-ia/terraform-aws-eks-blueprints-addons#348]
## Description

Testing the changes in  https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/339; this new issue has revealed itself:

```sh
kubectl logs -f -n karpenter -c controller -l app.kubernetes.io/name=karpenter
...
{"level":"ERROR","time":"2024-01-26T23:17:39.643Z","logger":"controller","message":"Reconciler error","commit":"1072d3b","controller":"nodeclass","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","EC2NodeClass":{"name":"default"},"namespace":"","name":"default","reconcileID":"670c192f-48c9-41b7-9aed-84c1f86163d6","error":"resolving instance profile, adding role \"karpenter-reproduction-20240126165825434100000005\" to instance profile \"reproduction_1945827343076045061\", AccessDenied: User: arn:aws-us-gov:sts::367652197469:assumed-role/karpenter-20240126230250710400000006/1706310212742318132 is not authorized to perform: iam:PassRole on resource: arn:aws-us-gov:iam::367652197469:role/karpenter-reproduction-20240126165825434100000005 because no identity-based policy allows the iam:PassRole action\n\tstatus code: 403, request id: cf4801ad-e7f6-47e5-b725-7f9269092cd2"}
```

I've attached the output from `tf show > file.hcl`.

- [x] I have searched the open/closed issues and a similar issue is listed:
https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/304
It's looking like a _regression_. 

Steps to reproduce:

1. Started with a reproduction cluster build
2. Added Karpenter config

```hcl
module "eks_blueprints_addons" {
  source  = "aws-ia/eks-blueprints-addons/aws"
  version = "~> 1.13.0"

  enable_karpenter                           = true
  karpenter_enable_instance_profile_creation = true
  # Added configuration show below
  karpenter = {
    irsa_tag_key    = "aws:ResourceTag/kubernetes.io/cluster/reproduction"
    irsa_tag_values = ["*"]
  }

  enable_metrics_server = true

  cluster_name      = module.eks.cluster_name
  cluster_endpoint  = module.eks.cluster_endpoint
  cluster_version   = module.eks.cluster_version
  oidc_provider_arn = module.eks.oidc_provider_arn
}
```

3. plan: good, apply (seemed) good (subnets/security groups are tagged)

4. Pushed the `NodePool` and `EC2NodeClass` config out

```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        name: default
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h # 30 * 24h = 720h
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2 # Amazon Linux 2
  role: "karpenter-reproduction-20240126165825434100000005"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "reproduction"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "reproduction"
```

Based on the logged error, it appears that the role, `"karpenter-reproduction-20240126165825434100000005"`, is connected to `karpenter-20240126230250710400000006` which does not have the correct security relationship(s). 

## Versions

```hcl
% tf version

Terraform v1.6.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.34.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.3
+ provider registry.terraform.io/hashicorp/helm v2.12.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.25.2
+ provider registry.terraform.io/hashicorp/time v0.10.0
+ provider registry.terraform.io/hashicorp/tls v4.0.5
```

## Reproduction Code [Required]

attached: 
[karpenter-post.zip](https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/files/14070182/karpenter-post.zip)

Not using workspaces.

## Additional context

This one is blocking me from testing #339. Once this one is fixed, we can likely close both 🤞

**Comment by vstthomas** [comment]
The reproduction code and supporting configs are here: (branch: `karpenter-iam`)
https://github.com/VivSoftOrg/reproduction/tree/karpenter-iam

**Comment by vstthomas** [comment]
I've retested, now I'm quite sure this was user/automation error; the `karpenter/EC2NodeClass` role wasn't updated properly for testing. 

```yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2 # Amazon Linux 2
  role: "karpenter-reproduction-2024013019241487490000000e" <- the role was misconfigured; should look like this
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "reproduction"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "reproduction"
```

![image](https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/assets/146481625/2208f0ea-3a79-4eeb-90c7-4f29b281104c)

Once this changed the errors evaprated.
