### ISSUE TITLE
Support for helm valueFiles

### ISSUE THREAD

**Issue by suchitsancheti** [aws-ia/terraform-aws-eks-blueprints-addons#40]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?
Need to add an argocd application which has overriding file. The terraform module for adding argocd application supports only adding values. Since, the overriding parameters are large, cannot use `values`

#### Describe the solution you would like
I am trying to add an argocd application from my git repo which has got an overriding file. I want to have an option like this:
```
  argocd_applications = {
    my-app = {
      ssh_key_secret_name = "github-repo-ssh-key"  # Needed for private repos
      namespace           = "argocd"
      path                = "argocd-app/k8s"
      repo_url            = "git@github.com:test/my-app.git"
      target_revision     = "HEAD"
      valueFiles          = "dev.yaml"
      type                = "helm"            # Optional, defaults to helm.
    }
  }
```

#### Additional context
I am trying to achieve argocd app of apps pattern by adding a repo which has got all the applications yaml with overriding files

**Comment by bryantbiggs** [comment]
thank you for the issue! At this time we are re-evaluating the integration between Terraform and GitOps operators like ArgoCD. We have removed the integration from the current project and will be tracking all feedback input in #114 while developing the next iteration of this integration

**Comment by taliesins** [comment]
@suchitsancheti we created a helm chart that creates argocd application object. This allows you to set properties of the application. You could even do an app of apps with this approach. 

values.yaml
```
# Application Name
name: ""
namespace: ""

# The ArgoCD Project the Application belongs to.
project: "default"

# Source config for the Application
source:

  # Git Repo the Application points to.
  repoUrl: ""

  # Target revision for the repo.
  targetRevision: "HEAD"

  # Path in the repo Argo should look for manifests.
  path: ""

  # Helm configuration.
  helm:
    releaseName: ""
    values: ""
    parameters: []

# Destination cluster.
destination:
  namespace: ""
  server: "https://kubernetes.default.svc"

```

templates/application.yaml
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  source:
    repoURL: {{ .Values.source.repoUrl }}
    targetRevision: {{ .Values.source.targetRevision }}
    path: {{ .Values.source.path }}
    {{- if or (.Values.source.helm.values) (gt (len .Values.source.helm.parameters) 0) }}
    helm:
      {{- if .Values.source.helm.releaseName }}
      releaseName: {{ .Values.source.helm.releaseName }}
      {{- end }}
      {{- if .Values.source.helm.values }}
      values: |
        {{- .Values.source.helm.values | nindent 8 }}
      {{- end }}
      {{- if (gt (len .Values.source.helm.parameters) 0) }}
      parameters:
        {{- range .Values.source.helm.parameters }}
        - {{- range $propertyName, $propertyValue := . }}
          {{- $propertyName | quote | nindent 10 }}: {{ $propertyValue | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: {{ .Values.destination.namespace }}
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
      - "Validate=false" # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default )
      - "CreateNamespace=true" # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
      - "PrunePropagationPolicy=foreground" # Supported policies are background, foreground and orphan.
      - "PruneLast=true" # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
    retry:
      backoff:
        duration: "10s"
        factor: 2
        maxDuration: "3m"

```
